// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: grpc/camera.proto

package camera

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CameraClient is the client API for Camera service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CameraClient interface {
	GetFrame(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type cameraClient struct {
	cc grpc.ClientConnInterface
}

func NewCameraClient(cc grpc.ClientConnInterface) CameraClient {
	return &cameraClient{cc}
}

func (c *cameraClient) GetFrame(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, "/camera.Camera/GetFrame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CameraServer is the server API for Camera service.
// All implementations must embed UnimplementedCameraServer
// for forward compatibility
type CameraServer interface {
	GetFrame(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedCameraServer()
}

// UnimplementedCameraServer must be embedded to have forward compatible implementations.
type UnimplementedCameraServer struct {
}

func (UnimplementedCameraServer) GetFrame(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrame not implemented")
}
func (UnimplementedCameraServer) mustEmbedUnimplementedCameraServer() {}

// UnsafeCameraServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CameraServer will
// result in compilation errors.
type UnsafeCameraServer interface {
	mustEmbedUnimplementedCameraServer()
}

func RegisterCameraServer(s grpc.ServiceRegistrar, srv CameraServer) {
	s.RegisterService(&Camera_ServiceDesc, srv)
}

func _Camera_GetFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraServer).GetFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/camera.Camera/GetFrame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraServer).GetFrame(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Camera_ServiceDesc is the grpc.ServiceDesc for Camera service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Camera_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camera.Camera",
	HandlerType: (*CameraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrame",
			Handler:    _Camera_GetFrame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/camera.proto",
}
